### ISSUE TITLE
相機電腦訊號線等設備架設

### ISSUE THREAD

**Issue by elishahung** [MoonShineVFX/4drec#23]

**Comment by elishahung** [comment]
本來底部預期會用120度的truss，但是因為底盤不相容改成用方形，但忘記方形只有30度可以配合，所以其實會歪掉，不能使用。
現在要想辦法讓最低點的相機有辦法架設。或許要利用2M的綠竿。

**Comment by elishahung** [comment]
![截圖 2020-07-27 下午7 54 27](https://user-images.githubusercontent.com/19182809/88539067-1b710780-d043-11ea-84a0-f24bd4cf24aa.png)
底部避免拉太長產生的震動，也找到將短桿鎖在方盒的方法，重新均勻分布相機位置。

**Comment by elishahung** [comment]
![IMG_1658](https://user-images.githubusercontent.com/19182809/88661259-d0222c00-d10a-11ea-866a-58b9e9daafee.jpg)
趁灌高雄NUC電腦時，先把鏡頭跟相機開箱跟組合。

**Comment by elishahung** [comment]
![截圖 2020-07-29 下午7 28 18](https://user-images.githubusercontent.com/19182809/88794858-ac75e900-d1d1-11ea-8102-bcc530de01e6.png)

等燈光架設的料件時，測量完所有相機要設定的焦距，準備調焦。
詳細資料在 https://docs.google.com/spreadsheets/d/1-vvbY-RZvGJj05Vejfu2K-Vu92gKK6SKWM11Vl9gu7o/edit?usp=sharing 表單裡。

對焦圖案已經列印，當初列印紙磅數有點買太薄，考慮再買厚一點的。
第一台預覽時會忽明忽暗，先架設燈光，之後再看是怎麼回事。
![IMG_3827](https://user-images.githubusercontent.com/19182809/88794924-c4e60380-d1d1-11ea-91ad-e412ec6511c4.jpg)

**Comment by elishahung** [comment]
有半天的時間在做林家齊的支線任務，灌新買的一堆nuc

調焦距調了一半，還剩DEF，另外發現4DC31這顆感光元件有壞點。
![IMG_5228](https://user-images.githubusercontent.com/19182809/89023168-b6285980-d355-11ea-9893-ff30e3af4f25.jpeg)

**Comment by elishahung** [comment]
相機都校準完了。

**Comment by elishahung** [comment]
先架了一組truss六台相機的整體測試。
![image](https://user-images.githubusercontent.com/19182809/89288971-10dcf080-d689-11ea-8fe7-835a7969256c.jpeg)
![image](https://user-images.githubusercontent.com/19182809/89288987-189c9500-d689-11ea-8141-2c4f7f7fe397.jpeg)
線都很長有點難整理，還在想怎麼整比較好看。
不過目前用一般折疊梯就可以架設不需要空中作業車，還不錯。

![image](https://user-images.githubusercontent.com/19182809/89289119-4c77ba80-d689-11ea-9f76-53a91ffc9c8e.jpeg)
但現在碰到slave抓不到相機的問題，usb隨身碟抓得到，相機連其他電腦也行，懷疑是系統有問題，明天再測試看看。

**Comment by elishahung** [comment]
絕望的一天，一整天都在找相機抓不到的問題，列一下測試的一些結果。

❌ 主機板 bios 韌體更新
❌ 相機韌體更新
❌ spinnaker 版本更新

交叉比對後判斷是 ccboot 跟系統有問題。

偵測不到相機的 USB 孔，拔掉改插隨身碟讀得到，換回相機仍然不行，裝置管理員會重新整理(閃一下)代表有偵測到，但完全不會列出來。

✅ 開機前先拔掉，進入 windows 再接上，可以偵測到。
✅ 開機前先拔掉，windows 讀取第二次轉圈時接上，可以偵測到
❌ 之後關掉再打開，就偵測不到。
❌ 更改 ccboot usbpnp 打開，偵測不到。
❌ 更改 ccboot usbpnp 打開，相機驅動刪除，直接系統死機。
✅ 用 ccboot 官方提供的鏡像，可以偵測到。
✅ 用 ubuntu live usb 可以偵測到。
✅ 灌一份 MBR BIOS 的本機 windows，可以偵測到。

如果真的無法，可能朝向用 ccboot 的鏡像來重新製作。

**Comment by elishahung** [comment]
❌ 用最早的 Windows server 2019 鏡像檔案，偵測不到。
✅ 用之前的 Windows server 2016 鏡像檔案，偵測得到。

看來是 windows server 2019 的問題...

**Comment by elishahung** [comment]
ccboot 的鏡像去設定完後，另外一台開機又偵測不到。
測試後發現只要在 usb port 有連相機的情況下製作 master ，就會造成之後偵測不到，不管驅動有沒有裝，也確認過不是相機問題，只要裝置管理員曾經出現過相機就會偵測不到。

**Comment by elishahung** [comment]
![IMG_5274](https://user-images.githubusercontent.com/19182809/89750780-fcbd4700-daff-11ea-8ca7-a37a8f86f9cb.jpeg)
測試單組連接、硬體同步快門、錄製儲存、讀取播放，都運作正常，唯一要注意的是 master 主機常常會變成公用網路，改私人網路才能讓 slave 連接(或改防火牆設定)。

![IMG_5277](https://user-images.githubusercontent.com/19182809/89750839-2f673f80-db00-11ea-93ae-a84224d90ab1.jpeg)
因應之後的架設跟先前留下的雜亂，大動作整理了一頓。

![IMG_5278](https://user-images.githubusercontent.com/19182809/89750857-4c037780-db00-11ea-844b-c93642a14aba.jpeg)
對先前的線路還是覺得雜亂，重新整線設計，同步訊號線跟網路線會走上端，相機出來的線會留50cm、65cm長變將訊號線纏繞在USB上。

**Comment by elishahung** [comment]
![IMG_5310](https://user-images.githubusercontent.com/19182809/89778037-61e45d00-db3f-11ea-9ef7-959d57b19b65.jpeg)
今天架第二組時，3.5mm訊號線拔掉時，頭整個斷掉(淘寶貨唉)，後來重新焊接一個新的，結果地線沒焊好，造成硬體快門驅動 debug 了很久，決定先購入標籤機，等把每條線都編號，再繼續裝設。

另外小心得：相機 USB孔不小心插錯孔，後來去插對的孔，也需要照一個順序去接速度才能正常。

USB孔問題真的很多，後悔沒用10G，不過那價錢也可怕。

![IMG_5311](https://user-images.githubusercontent.com/19182809/89778343-eb942a80-db3f-11ea-8f07-62efacb5d7c1.jpeg)
先把所有橫桿架完。

**Comment by elishahung** [comment]
![IMG_5330](https://user-images.githubusercontent.com/19182809/89893406-da642000-dc0a-11ea-8948-9e8c43022e16.jpeg)
架設所有相機、主機、主機電源線。

![IMG_5326](https://user-images.githubusercontent.com/19182809/89893449-f5cf2b00-dc0a-11ea-9629-d29d30fd60d6.jpeg)
![IMG_5327](https://user-images.githubusercontent.com/19182809/89893454-f798ee80-dc0a-11ea-8907-1dee65129616.jpeg)
標籤機來了，幫同步訊號線跟USB線標上編號以利之後除錯。

昨天壞的是36的訊號線，今天37的拔掉時也壞掉，這批便宜貨真的很脆弱，之後安裝時要小心絕對避免重複插拔。
另外忘記是42還是43，頭也已經解體，後來插回去幸好還是可以通，但之後要注意。

![IMG_5329](https://user-images.githubusercontent.com/19182809/89893728-7726bd80-dc0b-11ea-901e-6b6fe5abe5a0.jpeg)
把兩條訊號線重新焊新頭跟地線就都可以正常運作了，發現鑷子不會沾錫，可以很好控制線的形狀。

接下來就是把所有線編號跟把USB、訊號線做配對。

**Comment by elishahung** [comment]
### 出包幹
出了超級大包，需要大幅度思考未來方向。

這次避免像台北綠幕安裝時會屢次造成相機移位，將腳架鎖很緊。
想不到，鎖得太緊。
![IMG_2598](https://user-images.githubusercontent.com/19182809/90017105-9ee65600-dcdd-11ea-9906-1d988e80d8b8.jpg)
![IMG_4972](https://user-images.githubusercontent.com/19182809/90017114-a148b000-dcdd-11ea-9b77-626a15869a30.jpg)
共有 17 台相機故障(15台無法連接、2台畫面全雜訊)
基本上應該都是焊點脫落。

緊急聯絡林家齊後，先將這些相機送回台北，下禮拜一會有原廠的人來檢修。

### 擬定補救計畫：
![camera_reduction](https://user-images.githubusercontent.com/19182809/90017557-4a8fa600-dcde-11ea-9424-29c3e2f07322.png)
這邊在保持原本架構之下，每組先取消 4 台相機，用 32 台的概念去架設 (雖然只有 31 台)。
號碼需要重新對映臨時 32 台架構的新編號，[已設立對應表](https://docs.google.com/spreadsheets/d/1-vvbY-RZvGJj05Vejfu2K-Vu92gKK6SKWM11Vl9gu7o/edit#gid=0)。

線與主機的部分就還是保持原本 48 台的架構去組裝，保留日後如果能維修且修好的彈性。

### 相機備援計畫
另外有個選擇性計畫，是拿台北 500 萬畫素的相機來頂替不足的部分，每台相機需要多添購 USB3 轉 RJ45 的轉接線跟 POE injector。

### 軟體更動部分
這個之後會再開 issue，先列一下

- 相機編號的嚴格定義與臨時定義，介面上隨之的調整。

- 如果使用 500 萬畫素相機，解析度不同同時存在的對應設定。

**Comment by elishahung** [comment]
### 硬體關係的結構更改
相機編號跟臨時編號這種方式太亂了，重新劃分成 truss 的**位置編號**與**相機編號**兩種定義，增加相容性跟可識別度。

- 相機編號: 就是原本編號
- 位置編號: 依照 Truss 分成 A~H，再依照順序分 0~5，譬如**G3**。

與之相應就去做了各種更新：
![註解 2020-08-13 173031](https://user-images.githubusercontent.com/19182809/90137096-b8ec6b00-dda7-11ea-8712-195b6d0310e9.png)
- Sketchup: 重新命名位置編號。
- [4DK相機表](https://docs.google.com/spreadsheets/d/1-vvbY-RZvGJj05Vejfu2K-Vu92gKK6SKWM11Vl9gu7o/edit#gid=314009765): 重新規劃欄位，更可以了解目前哪來相機在哪個位置上。
- 擷取程式: 參照 56dceb4 ，可以更容易去轉移相機位置與 slave 的連接關係，經測試已正常運作。

接下來就是按照新的規劃，這禮拜完成所有線路組裝。

**Comment by elishahung** [comment]
![IMG_5379](https://user-images.githubusercontent.com/19182809/90311706-8457eb00-df30-11ea-9062-8fa08ddca908.jpeg)
線路48個位置都終於接完了，目前僅有的31台相機也能正常運作，這兩天都順利進行沒遇到出錯。

接下來是網路線的牽線，比想像中的麻煩，看來週末兩天都需要加班。
![IMG_5385](https://user-images.githubusercontent.com/19182809/90311729-dac52980-df30-11ea-947a-b9d650260aa8.jpeg)
![IMG_5387](https://user-images.githubusercontent.com/19182809/90311731-def14700-df30-11ea-8d5e-1207b463c627.jpeg)

**Comment by elishahung** [comment]
![IMG_9B55F43CF768-1](https://user-images.githubusercontent.com/19182809/90329595-c76d9900-dfd8-11ea-8205-e74426fbb24f.jpeg)
今天把剩下另一半部網路線拉完，有了昨天的經驗，這次先把線給順好後，好整理很多。

![IMG_5391](https://user-images.githubusercontent.com/19182809/90329616-fbe15500-dfd8-11ea-86ef-ab05279b3db1.jpeg)
總算全部設備架設都完成了(壞掉的相機不算的話)
全部開機測試快門、錄影、讀取都順利運作。

![IMG_5392](https://user-images.githubusercontent.com/19182809/90329638-2c28f380-dfd9-11ea-8da5-f57ae842e2d4.jpeg)
![IMG_5393](https://user-images.githubusercontent.com/19182809/90329641-3945e280-dfd9-11ea-8ce8-946ef0f2795a.jpeg)
沒有整線槽，先將就這樣牽。

**Comment by elishahung** [comment]
https://www.youtube.com/watch?v=ZS6uYTvQ1qo&feature=youtu.be
上週末放算了一整個禮拜監視器 timelapse 😂

**Comment by davidlatwe** [comment]
> https://www.youtube.com/watch?v=ZS6uYTvQ1qo&feature=youtu.be
上週末放算了一整個禮拜監視器 timelapse 😂

嗚哇～～
